INSERT INTO public.tbl_states (state_id, code, name) VALUES (1, 'AGO', 'Angola');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (2, 'ALB', 'Albania');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (3, 'AND', 'Andorra');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (4, 'ARE', 'United Arab Emirates');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (5, 'ARG', 'Argentina');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (6, 'ARM', 'Armenia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (7, 'ATG', 'Antigua and Barbuda');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (8, 'AUS', 'Australia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (9, 'AUT', 'Austria');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (10, 'AZE', 'Azerbaijan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (11, 'BDI', 'Burundi');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (12, 'BEL', 'Belgium');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (13, 'BEN', 'Benin');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (14, 'BFA', 'Burkina Faso');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (15, 'BGD', 'Bangladesh');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (16, 'BGR', 'Bulgaria');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (17, 'BHR', 'Bahrain');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (18, 'BHS', 'Bahamas');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (19, 'BIH', 'Bosnia and Herzegovina');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (20, 'BLR', 'Belarus');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (21, 'BLZ', 'Belize');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (22, 'BOL', 'Bolivia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (23, 'BRA', 'Brazil');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (24, 'BRB', 'Barbados');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (25, 'BRN', 'Brunei Darussalam');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (26, 'BTN', 'Bhutan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (27, 'BWA', 'Botswana');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (28, 'CAF', 'Central African Republic');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (29, 'CAN', 'Canada');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (30, 'CHE', 'Switzerland');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (31, 'CHL', 'Chile');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (32, 'CHN', 'China');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (33, 'CIV', 'Cote d''Ivoire');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (34, 'CMR', 'Cameroon');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (35, 'COD', 'Democratic Republic of the Congo');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (36, 'COG', 'Congo');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (37, 'COK', 'Cook Islands');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (38, 'COL', 'Colombia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (39, 'COM', 'Comoros');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (40, 'CPV', 'Cabo Verde');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (41, 'CRI', 'Costa Rica');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (42, 'CUB', 'Cuba');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (43, 'CYP', 'Cyprus');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (44, 'CZE', 'Czech Republic');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (45, 'DEU', 'Germany');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (46, 'DJI', 'Djibouti');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (47, 'DNK', 'Denmark');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (48, 'DOM', 'Dominican Republic');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (49, 'DZA', 'Algeria');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (50, 'ECU', 'Ecuador');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (51, 'EGY', 'Egypt');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (52, 'ERI', 'Eritrea');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (53, 'ESP', 'Spain');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (54, 'EST', 'Estonia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (55, 'ETH', 'Ethiopia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (56, 'FIN', 'Finland');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (57, 'FJI', 'Fiji');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (58, 'FRA', 'France');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (59, 'FSM', 'Micronesia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (60, 'GAB', 'Gabon');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (61, 'GBR', 'United Kingdom of Great Britain and Northern Ireland');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (62, 'GEO', 'Georgia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (63, 'GHA', 'Ghana');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (64, 'GIN', 'Guinea');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (65, 'GMB', 'Gambia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (66, 'GNB', 'Guinea-Bissau');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (67, 'GNQ', 'Equatorial Guinea');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (68, 'GRC', 'Greece');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (69, 'GRD', 'Grenada');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (70, 'GTM', 'Guatemala');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (71, 'GUY', 'Guyana');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (72, 'HND', 'Honduras');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (73, 'HRV', 'Croatia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (74, 'HTI', 'Haiti');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (75, 'HUN', 'Hungary');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (76, 'IDN', 'Indonesia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (77, 'IND', 'India');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (78, 'IRL', 'Ireland');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (79, 'IRN', 'Iran');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (80, 'ISL', 'Iceland');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (81, 'ISR', 'Israel');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (82, 'ITA', 'Italy');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (83, 'JAM', 'Jamaica');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (84, 'JOR', 'Jordan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (85, 'JPN', 'Japan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (86, 'KAZ', 'Kazakhstan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (87, 'KEN', 'Kenya');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (88, 'KGZ', 'Kyrgyzstan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (89, 'KHM', 'Cambodia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (90, 'KNA', 'Saint Kitts and Nevis');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (91, 'KOR', 'Republic of Korea');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (92, 'KWT', 'Kuwait');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (93, 'LAO', 'Lao People''s Democratic Republic');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (94, 'LBN', 'Lebanon');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (95, 'LBR', 'Liberia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (96, 'LBY', 'Libya');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (97, 'LCA', 'Saint Lucia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (98, 'LKA', 'Sri Lanka');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (99, 'LSO', 'Lesotho');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (100, 'LTU', 'Lithuania');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (101, 'LUX', 'Luxembourg');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (102, 'LVA', 'Latvia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (103, 'MAR', 'Morocco');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (104, 'MCO', 'Monaco');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (105, 'MDA', 'Republic of Moldova');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (106, 'MDG', 'Madagascar');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (107, 'MDV', 'Maldives');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (108, 'MEX', 'Mexico');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (109, 'MHL', 'Marshall Islands');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (110, 'MKD', 'The former Yugoslav Republic of Macedonia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (111, 'MLI', 'Mali');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (112, 'MLT', 'Malta');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (113, 'MMR', 'Myanmar');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (114, 'MNE', 'Montenegro');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (115, 'MNG', 'Mongolia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (116, 'MOZ', 'Mozambique');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (117, 'MRT', 'Mauritania');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (118, 'MUS', 'Mauritius');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (119, 'MWI', 'Malawi');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (120, 'MYS', 'Malaysia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (121, 'NAM', 'Namibia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (122, 'NER', 'Niger');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (123, 'NGA', 'Nigeria');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (124, 'NIC', 'Nicaragua');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (125, 'NLD', 'Netherlands');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (126, 'NOR', 'Norway');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (127, 'NPL', 'Nepal');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (128, 'NRU', 'Nauru');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (129, 'NZL', 'New Zealand');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (130, 'OMN', 'Oman');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (131, 'PAK', 'Pakistan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (132, 'PAN', 'Panama');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (133, 'PER', 'Peru');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (134, 'PHL', 'Philippines');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (135, 'PLW', 'Palau');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (136, 'PNG', 'Papua New Guinea');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (137, 'POL', 'Poland');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (138, 'PRK', 'Democratic People''s Republic of Korea');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (139, 'PRT', 'Portugal');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (140, 'PRY', 'Paraguay');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (141, 'QAT', 'Qatar');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (142, 'ROU', 'Romania');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (143, 'RUS', 'Russian Federation');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (144, 'RWA', 'Rwanda');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (145, 'SAU', 'Saudi Arabia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (146, 'SDN', 'Sudan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (147, 'SEN', 'Senegal');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (148, 'SGP', 'Singapore');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (149, 'SLB', 'Solomon Islands');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (150, 'SLE', 'Sierra Leone');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (151, 'SLV', 'El Salvador');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (152, 'SMR', 'San Marino');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (153, 'SRB', 'Serbia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (154, 'STP', 'Sao Tome and Principe');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (155, 'SUR', 'Suriname');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (156, 'SVK', 'Slovakia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (157, 'SVN', 'Slovenia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (158, 'SWE', 'Sweden');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (159, 'SWZ', 'Swaziland');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (160, 'SYC', 'Seychelles');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (161, 'SYR', 'Syrian Arab Republic');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (162, 'TCD', 'Chad');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (163, 'TGO', 'Togo');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (164, 'THA', 'Thailand');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (165, 'TJK', 'Tajikistan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (166, 'TKM', 'Turkmenistan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (167, 'TLS', 'Timor-Leste');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (168, 'TON', 'Tonga');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (169, 'TTO', 'Trinidad and Tobago');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (170, 'TUN', 'Tunisia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (171, 'TUR', 'Turkey');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (172, 'TZA', 'United Republic of Tanzania');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (173, 'UGA', 'Uganda');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (174, 'UKR', 'Ukraine');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (175, 'URY', 'Uruguay');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (176, 'USA', 'United States of America');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (177, 'UZB', 'Uzbekistan');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (178, 'VCT', 'Saint Vincent and the Grenadines');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (179, 'VEN', 'Venezuela');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (180, 'VNM', 'Viet Nam');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (181, 'VUT', 'Vanuatu');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (182, 'WSM', 'Samoa');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (183, 'ZAF', 'South Africa');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (184, 'ZMB', 'Zambia');
INSERT INTO public.tbl_states (state_id, code, name) VALUES (185, 'ZWE', 'Zimbabwe');
